"use client";
import {useEffect,useState} from "react";
type TeacherQuiz={id:string;title:string;status:string;attempts:Array<unknown>}; type TeacherClass={id:string;name:string}; type Analytics={attempted:number;assigned:number;average:number;highest:number;lowest:number;completionRate:number};
export default function TeacherDashboard({user}:{user:{name:string}}){
 const[q,setQ]=useState<TeacherQuiz[]>([]),[classes,setClasses]=useState<TeacherClass[]>([]),[title,setTitle]=useState(""),[classId,setClassId]=useState(""),[analytics,setAnalytics]=useState<Record<string,Analytics>>({}),[busy,setBusy]=useState<string|null>(null);
 async function load(){const[a,b]=await Promise.all([fetch("/api/quizzes"),fetch("/api/classes")]);const qa=(await a.json()) as {quizzes?:TeacherQuiz[]};const ca=(await b.json()) as {classes?:TeacherClass[]};setQ(qa.quizzes??[]);setClasses(ca.classes??[])}
 useEffect(()=>{void load()},[]);
 async function create(){const now=new Date();const body={title,description:"Created from teacher dashboard",opensAt:now.toISOString(),closesAt:new Date(now.getTime()+86400000).toISOString(),durationMinutes:20,pointsPerQuestion:1,negativeMarkPercent:0,classId,questions:[{text:"Sample question",options:[{text:"Correct",isCorrect:true},{text:"Incorrect",isCorrect:false},{text:"Incorrect",isCorrect:false},{text:"Incorrect",isCorrect:false}]}]};const r=await fetch("/api/quizzes/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){setTitle("");await load()}}
 async function publish(id:string){setBusy(id);const r=await fetch("/api/quizzes/"+id+"/publish",{method:"POST"});if(r.ok)await load();setBusy(null)}
 async function showAnalytics(id:string){const r=await fetch("/api/analytics/"+id);if(r.ok){const data=(await r.json()) as Analytics;setAnalytics(prev=>({...prev,[id]:data}))}}
 return <main className="shell"><div className="top"><div><p className="muted">Teacher</p><h1>{user.name}</h1></div><button className="btn secondary" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}}>Sign out</button></div>
 <div className="card"><h2>Create quiz</h2><div className="row"><input aria-label="Quiz title" className="input" style={{maxWidth:360}} placeholder="Quiz title" value={title} onChange={e=>setTitle(e.target.value)}/><select aria-label="Class" className="input" style={{maxWidth:260}} value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn" disabled={!title||!classId} onClick={create}>Create draft</button></div></div>
 <div className="card" style={{marginTop:16}}><h2>Quizzes</h2>{!q.length&&<p className="muted">No quizzes yet.</p>}{q.map(x=><div key={x.id} style={{padding:"14px 0",borderBottom:"1px solid #e2e8f0"}}><div><b>{x.title}</b><span className="muted"> · {x.status} · {x.attempts.length} submitted attempts</span></div><div className="row" style={{marginTop:8}}>{x.status==="DRAFT"&&<button className="btn" disabled={busy===x.id} onClick={()=>publish(x.id)}>{busy===x.id?"Publishing…":"Publish"}</button>}<button className="btn secondary" onClick={()=>showAnalytics(x.id)}>Analytics</button></div>{analytics[x.id]&&<p className="muted">Attempted {analytics[x.id].attempted}/{analytics[x.id].assigned} · Average {analytics[x.id].average} · High {analytics[x.id].highest} · Low {analytics[x.id].lowest} · Completion {analytics[x.id].completionRate}%</p>}</div>)}</div></main>
}